version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: usuarios
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: db_atv4
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    ports:
      - "3010:3000"
    depends_on:
      - db

volumes:
  db_data: